config/routes.rb
Rails.application.routes.draw do
  resources :tags
  devise_for :users
  root "static_pages#home"

  resources :usernames, only: [:new, :update]

  resources :projects do
    resources :comments
  end
  
  resources :posts do
    resources :comments
  end

  resources :likes, only: [:create, :destroy]

  resources :users

 get '/:username', to: 'profiles#show', as: :profile
 get '/:username/comments', to: 'profiles#profile_comments', as: :profile_comments
 patch '/:username/edit', to: 'profiles#update', as: :update_profile

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true, counter_cache: :comments_count
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :comments, dependent: :destroy, foreign_key: :parent_id

  validates :body, presence: true, length: { minimum: 1, maximum: 5000}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_commentable
    before_action :find_comment, only: :destroy

    def create
        @comment = @commentable.comments.new(comment_params)
        @comment.user = current_user
        flash[:notice] = "Comment successfully created"
        if @comment.save
            respond_to do |format|
                format.html { redirect_to @commentable }
                # format.turbo_stream
            end
        else
            flash[:notice] = @comment.errors.full_messages.join(", ")
            redirect_to @commentable
        end
    end

    def edit
      
    end

    def destroy
        @comment.destroy
        flash[:notice] = "Comment successfully deleted."
        redirect_to @commentable
    end

    private

    def find_comment
        @comment ||= Comment.find(params[:id])
    end

    def comment_params
        params.require(:comment).permit(:body, :parent_id)
    end

    def set_commentable
        if params[:project_id].present?
            @commentable = Project.find(params[:project_id])
        elsif params[:comment_id].present?
            @commentable = Comment.find(params[:comment_id])
        elsif params[:post_id].present?
            @commentable = Post.find(params[:post_id])
        end
    end
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag comment do %>

    <div class="comment ps-3">
        <div class="mb-3">
            <p class="m-0 fw-bold"><small><span class="text-muted">comment by: </span><%= link_to comment.user.username, profile_path(comment.user.username), class: "text-dark" %>, <%= time_ago_in_words(comment.created_at) %> ago</small></p>
            <p class="m-0"><%= comment.body %></p>
            <p><%= comment.comments.count %></p>

            <% if current_user %>
                <%= link_to 'edit', edit_post_comment_path(@post, comment), class: "text-decoration-none text-dark m-0" if comment.commentable_type == 'Post' && comment.user == current_user %> 
                
                <%= link_to 'edit', edit_project_comment_path(@project, comment), class: "text-decoration-none text-dark m-0" if comment.commentable_type == 'Project' && comment.user == current_user %> |
                <%= link_to "delete", [@commentable, comment], data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" }, class: "text-decoration-none text-dark m-0" %> |

                <%= link_to "reply", '#', class: "text-dark text-decoration-none m-0 comment-form-display" %>
            <% end %>

            <div class="sub-comment-form">
                <%= render partial: 'comments/form', locals: { commentable: @commentable, parent: comment } %>
            </div>
        </div>

        <%#= comment.comments_count %>

        <div class="sub-comments">
            <%= render comment.comments.order(id: :desc) %>
        </div>
    </div>
<% end %>

<script>
    document.querySelectorAll('.comment-form-display').forEach((el) => {
        el.addEventListener('click', (ev) => {
            ev.preventDefault();
            el.nextElementSibling.style = 'display: block';
        })
    })
</script>

app/views/comments/_form.html.erb
    <%= form_with(model: [commentable, @comment]) do |f| %>

        <% if @comment.errors.any? %>
            <div id="error_explanation">
                <div class="alert alert-danger">
                    The form contains <%= pluralize(@comment.errors.count, "error") %>
                </div>
                <ul>
                    <% @comment.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <% if !parent.nil? %>
            <%= f.hidden_field :parent_id, value: parent.id %>
        <% end %>

        <div class="mb-3">
            <%= f.text_area :body, placeholder: "Type your comment", class: "form-control", rows: "5" %>
        </div>

        <div class="mb-3">
            <% if parent.nil? %>
                <%= f.submit "Submit comment", class: "btn btn-dark" %>
            <% else %>
                <%= f.submit "Reply comment", class: "btn btn-dark" %>
                <%= link_to "cancel", [commentable, @comment], class: "btn btn-light border text-decoration-none" %>
            <% end %>
        </div>
    <% end %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
    <%= render 'form', commentable: @comment.commentable %>
<% end %>