config/routes.rb
Rails.application.routes.draw do
  resources :tags
  devise_for :users
  root "static_pages#home"

  resources :usernames, only: [:new, :update]

  resources :projects do
    resources :comments
  end
  
  resources :posts do
    resources :comments
  end

  resources :likes, only: [:create, :destroy]

  resources :users

 get '/:username', to: 'profiles#show', as: :profile
 get '/:username/comments', to: 'profiles#profile_comments', as: :profile_comments
 patch '/:username/edit', to: 'profiles#update', as: :update_profile

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  self.per_page = 6

  has_many :likes, as: :likeable

  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings

  has_many :comments, as: :commentable

  has_one_attached :image do |attachable|
    attachable.variant :display, resize_to_limit: [500, 500]
  end

  has_rich_text :description

  validates :title, :description, :github_link, presence: true

  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "must be a valid image format" },
                      size: { less_than: 5.megabytes,
                              message:   "should be less than 5MB" }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_user!, only: %i[ new create edit update destroy ]
    before_action :find_project, only: %i[ edit show update destroy ]
    before_action :correct_user, only: %i[ edit update destroy ]

    def index
        @projects = Project.includes(:user, image_attachment: :blob).paginate(page: params[:page]).order(created_at: :desc)
    end

    def new
        @project = Project.new
    end

    def create
        @project = current_user.projects.build(project_params)
        if @project.save
            
            redirect_to @project, notice: 'Project was successfully created'
        else
            render 'new', status: :unprocessable_entity, notice: current_user.errors.full_messages.join(", ")
        end
    end

    def show
        @commentable = @project
        @comment = Comment.new
    end

    def edit
    end

    def update
        if @project.update(project_params)
            flash[:notice] = "Project successfully updated"
            redirect_to @project
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def destroy
        @project.destroy
        flash[:notice] = "Project deleted successfully"
        redirect_to projects_url
    end

    private

        def project_params
            params.require(:project).permit(:title, :description, :github_link, :preview_link, :image, tag_ids: [])
        end

        def find_project
            @project ||= Project.find(params[:id])
        end

        # confirms the correct user
        def correct_user
            @project ||= Project.find(params[:id])
            redirect_to(projects_url, status: :see_other, notice: "Access denied") unless current_user.admin?
        end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with model: @project do |f| %>

    <% if @project.errors.any? %>
        <div id="error_explanation">
            <div class="alert alert-danger">
                The form contains <%= pluralize(@project.errors.count, "error") %>
            </div>
            <ul>
                <% @project.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="mb-3">
        <h5><%= f.label :title %></h5>
        <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="mb-3">
        <h5><%= f.label :description %></h5>
        <%= f.rich_text_area :description, class: "form-control" %>
    </div>

    <div class="mb-3">
        <h5><%= f.label :github_link %></h5>
        <%= f.text_field :github_link, class: "form-control" %>
    </div>

    <div class="mb-3">
        <h5><%= f.label :preview_link, "Preview link/demo" %></h5>
        <%= f.text_field :preview_link, class: "form-control" %>
    </div>

    <div class="mb-3">
        <h5><%= f.label :image, class: "form-label" %></h5>
        <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png", class: "form-control" %>
    </div>

    <div class="mb-3" data-controller="tom-select">
        <h5><%= f.label :tags, class: "form-label" %></h5>
        <%#= f.select :tag_ids, Tag.where(category: "project").pluck(:name, :id), {}, { multiple: true, id: "select-tags" } %>
        <%= f.select :tag_ids, Tag.all.pluck(:name, :id), {}, { multiple: true, id: "select-tags" } %>
    </div>

    <div class="mb-3">
        <%= f.submit "Submit project", class: "btn btn-dark rounded-pill" %>
    </div>
<% end %>

app/views/projects/_project.html.erb
<div class="col-md-4 pb-3 card">
    <div class="project-card rounded pb-3 h-100">
        <div class="project-img mb-3">
            <% if project.image.attached? %>
                <%= link_to project do %>
                    <%= image_tag project.image, class: "img-fluid" %>
                <% end %>
            <% else %>
                <%= link_to project do %>
                    <%= image_tag 'default-webpage.jpg', class: "img-fluid" %>
                <% end %>
            <% end %>
        </div>
        <div class="px-2">
            <h5 class="project-title"><%= link_to project.title, project, class: "text-dark text-decoration-none" %></h5>
            <div class="project-tags">
                <% project.tags.each do |tag| %>
                    <%= link_to tag.name, tag, class: "btn btn-light btn-sm text-sm border" %>
                <% end %>
            </div>
            <p class="project-copy text-sm text-justify"><%= project.description.to_plain_text.truncate(100) %></p>
            <div class="mt-3">
                <% if project.preview_link.present? %>
                    <%= link_to project.preview_link, class: "btn btn-light border-dark me-2 btn-sm" do %>
                        <i class="bi bi-box-arrow-up-right"></i>
                        Preview
                    <% end %>
                <% end %>
                <%= link_to project.github_link, class: "btn btn-dark me-2 btn-sm" do %>
                    <i class="bi bi-github"></i>
                    Github
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/projects/edit.html.erb
<% provide(:title,  "Edit #{@project.title}") %>

<div class="container py-5" style="max-width: 540px">
    <div>
        <%= link_to @project, class: "text-dark" do %>
            <span><i class="bi bi-arrow-left fs-1"></i></span>
            <%# <span class="back">back</span> %>
        <% end %>
    </div>
    <div class="project-copy">
        <h1 class="mb-3">Edit Project</h1>

        <%= render 'form' %>
    </div>
</div>

app/views/projects/index.html.erb
<% provide(:title, "My projects") %>

<div class="container py-5 text-center">
    <%= link_to "New project", new_project_path, class: "btn btn-dark rounded-pill mb-3" if user_signed_in? && current_user.admin %>
    <div class="project-copy my-3">
        <h1>Projects</h1>
        <!--<p>I have worked over the months on different levels of rails applications. The experienced acquired from these has equipped me with enough knowledge totake on any rails app.</p>-->
    </div>

    <div id="projects" class="row">
        <%= render @projects %>
    </div>

    <div class="text-center mt-2">
        <%= will_paginate(@projects) %>
    </div>
</div>

app/views/projects/index.turbo_stream.erb
<%= turbo_stream.append :projects do %>
    <%= render @projects %>
<% end %>

<%= turbo_stream.replace :pagination do %>
    <%= turbo_frame_tag :pagination, loading: :lazy, src: projects_path(format: :turbo_streams) %>
<% end %>

app/views/projects/new.html.erb
<% provide(:title, 'New project') %>

<div class="container py-5" style="max-width: 540px">
    <%= link_to :back, class: "text-dark" do %>
        <span><i class="bi bi-arrow-left fs-1"></i></span>
        <%# <span class="back">back</span> %>
    <% end %>
    
    <div class="project-copy">
        <h1 class="mb-3">New Project</h1>

        <%= render 'form' %>
    </div>
</div>

app/views/projects/show.html.erb
<% provide(:title, @project.title) %>

<div class="container py-3" style="max-width: 800px">
    <div class="d-flex justify-content-between">
        <%= link_to projects_path, class: "text-dark" do %>
            <span><i class="bi bi-arrow-left fs-1"></i></span>
            <%# <span class="back">back</span> %>
        <% end %>

        <%= link_to "New project", new_project_path, class: "btn btn-dark mt-2 mb-3 text-decoration-none" %>
        <span class="dropdown">
            <% if user_signed_in? && @project.user == current_user %>
                <div style="cursor:pointer;" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-three-dots-vertical fs-3"></i>
                </div>
                <ul class="dropdown-menu">
                    <%= link_to edit_project_path(@project), class: "dropdown-item" do %>
                        <i class="bi bi-pen"></i>
                        Edit
                    <% end %>
                    <%= link_to @project, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this post" }, class: "dropdown-item" do %>
                        <i class="bi bi-trash"></i>
                        Delete
                    <% end %>
                </ul>
            <% end %>
        </span>
    </div>
    <div class="project">
        <div class="text-center">
            <h1 class="mb-3"><%= @project.title %></h1>
            <div class="project-tags">
                <% @project.tags.each do |tag| %>
                    <%= link_to tag.name, tag, class: "btn btn-light btn-sm border text-sm" %>
                <% end %>
            </div>
            <p class="text-muted">Posted by <%= link_to @project.user.username, profile_path(@project.user.username), class: "text-muted text-decoration-none" %>, <%= time_ago_in_words(@project.created_at) %>
            <div class="project-img mb-3">
                <% if @project.image.attached? %>
                    <%= image_tag @project.image, class: "img-fluid" %>
                <% else %>
                    <%= image_tag 'default-webpage.jpg', class: "img-fluid" %>
                <% end %>
            </div>
            <span>
                <%= link_to "Github link", @project.github_link, target: "_blank", class: "btn btn-dark rounded-pill mt-2 mb-3 text-decoration-none" %>
                <%= link_to "Preview link", @project.preview_link, target: "_blank", class: "btn btn-light border rounded-pill mt-2 mb-3 text-decoration-none" if @project.preview_link.present? %>
            </span>
        </div>
        <p><%= @project.description %></p>
        <div class="text-center">
            <%= render partial: "likes/button", locals: { likeable: @project } %>
        </div>
    </div>

    <section class="comments mt-4 pb-3 border p-3" style="font-size: 15px;">
        <h2 class="text-center">Comments (<%= @project.comments_count %>)</h2>
        <%= render @project.comments.where(parent_id: nil).includes(:user).order(id: :desc) %>
        <h6 class="pt-3">New comment:</h6>
        <div id="comment-form" class="comment-form mt-2">
            <%= render 'comments/form', commentable: @commentable, parent: nil %>
        </div>
    </section>
</div>