config/routes.rb
Rails.application.routes.draw do
  resources :tags
  devise_for :users
  root "static_pages#home"

  resources :usernames, only: [:new, :update]

  resources :projects do
    resources :comments
  end
  
  resources :posts do
    resources :comments
  end

  resources :likes, only: [:create, :destroy]

  resources :users

 get '/:username', to: 'profiles#show', as: :profile
 get '/:username/comments', to: 'profiles#profile_comments', as: :profile_comments
 patch '/:username/edit', to: 'profiles#update', as: :update_profile

end

app/models/tag.rb
class Tag < ApplicationRecord
    before_save :downcase_name
    
    validates :name, presence: true, uniqueness: true
	validates :name, length: {minimum: 2, maximum: 15}
    has_many :taggings, dependent: :destroy
    
    has_many :projects, :through => :taggings, :source => :taggable, :source_type => 'Project'

    has_many :posts, :through => :taggings, :source => :taggable, :source_type => 'Post'

    private

    # Converts name to all lowercase.
    def downcase_name
        self.name.downcase!
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new create edit update destroy ]
  before_action :correct_user, only: %i[ edit update destroy ]
  before_action :correct_create_user, only: %i[ create new ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)
    # redirect_to(root_url, status: :see_other, notice: "Access denied") unless current_user && current_user.admin?

    if @tag.valid?
      @tag.save
      render json: @tag
    else
      flash[:notice] = @tag.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path, status: :unprocessable_entity)
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end

    # confirms the correct user
    def correct_user
      @tag ||= Tag.find(params[:id])
      redirect_to(root_url, status: :see_other, notice: "Access denied") unless current_user && current_user.admin?
    end

    # confirms the correct user
    def correct_create_user
      redirect_to(root_url, status: :see_other, notice: "Access denied") unless current_user && current_user.admin?
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <% if tag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <h5><%= form.label :name, style: "display: block" %></h5>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <br>

  <div>
    <%= form.submit "Create tag", class: "btn btn-dark" %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <p>
    <strong>Name:</strong>
    <%= tag.name %>
  </p>

</div>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Show this tag", @tag %> |
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/index.html.erb
<% provide(:title, "Tags") %>

<div class="container py-5 text-center">
  <%= link_to "New tag", new_tag_path, class: "btn btn-dark rounded-pill mb-3" %>
  <div class="project-copy">
      <h1 class="pb-3">Tags</h1>
      <% @tags.each do |tag| %>
        <%= link_to tag.name, tag, class: "btn btn btn-light border" %>
      <% end %>
  </div>
</div>

app/views/tags/new.html.erb
<% provide(:title, 'New tag') %>

<div class="container py-5" style="max-width: 540px">
    <%= link_to tags_path, class: "text-dark" do %>
        <span><i class="bi bi-arrow-left fs-1"></i></span>
        <%# <span class="back">back</span> %>
    <% end %>
    
    <div class="project-copy">
        <h1 class="mb-3">New Tag</h1>

        <%= render 'form', tag: @tag %>
    </div>
</div>

app/views/tags/show.html.erb
<% provide(:title, @tag.name) %>

<div class="container py-5 text-center">
  <%= link_to "New tag", new_tag_path, class: "btn btn-dark rounded-pill mb-3" %>
  <h2 class="pb-3"><%= @tag.name %></h2>
  <div class="row">
      <% @tag.projects.each do |project| %>
        <%= render partial: 'projects/project', locals: { project: project } %>
      <% end %>
  </div>
</div>