config/routes.rb
Rails.application.routes.draw do
  resources :tags
  devise_for :users
  root "static_pages#home"

  resources :usernames, only: [:new, :update]

  resources :projects do
    resources :comments
  end
  
  resources :posts do
    resources :comments
  end

  resources :likes, only: [:create, :destroy]

  resources :users

 get '/:username', to: 'profiles#show', as: :profile
 get '/:username/comments', to: 'profiles#profile_comments', as: :profile_comments
 patch '/:username/edit', to: 'profiles#update', as: :update_profile

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 10, maximum: 500 }
  validates :body, presence: true, length: { minimum: 500 }

  belongs_to :user, counter_cache: :posts_count
  has_many :comments, as: :commentable

  has_many :likes, as: :likeable

  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings

  has_one_attached :image do |attachable|
    attachable.variant :display, resize_to_limit: [500, 500]
  end

  has_rich_text :body

  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "must be a valid image format" },
                      size: { less_than: 5.megabytes,
                              message:   "should be less than 5MB" }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    before_action :correct_user, only: %i[ edit update destroy ]

    def index
        @posts = Post.includes(:user, :comments, :likes, image_attachment: :blob).order(created_at: :desc)
    end

    def new
        @post = current_user.posts.new
    end

    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            flash[:notice] = "Post created successfully"
            redirect_to @post
        else
            render :new
        end
    end

    def show
        @commentable = @post
        @comment = Comment.new
    end

    def edit
        
    end

    def update
        if @post.update(post_params)
            flash[:notice] = "Post updated successfully"
            redirect_to @post
        else
            render :edit
        end
    end

    private

    def post_params
        params.require(:post).permit(:title, :body, :image, tag_ids: [])
    end

    def find_post
        @post ||= Post.find(params[:id]) 
    end

    # confirms the correct user
    def correct_user
        @post ||= Post.find(params[:id])
        redirect_to(posts_url, status: :see_other, notice: "Access denied") unless current_user.admin?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_button.html.erb
<% like = current_user.likes.find_by(likeable: likeable) %>

<% if like.nil? %>  
    <%= button_to(likes_path, class:"btn btn-light border fs-4",  params:{ like: {likeable_id: likeable.id,  likeable_type: likeable.class.to_s}}) do %>
        <i class="bi bi-suit-heart"></i>
        <%= @post.likes_count %>
    <% end %>
<% else %>  
    <%= button_to(like_path(like), class:"btn btn-light border fs-4", method: :delete) do %>
        <i class="bi bi-suit-heart-fill"></i>
        <%= @post.likes_count %>
    <% end %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: @post do |f| %>

    <% if @post.errors.any? %>
        <div id="error_explanation">
            <div class="alert alert-danger">
                The form contains <%= pluralize(@post.errors.count, "error") %>
            </div>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="mb-3">
        <h5><%= f.label :title %></h5>
        <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="mb-3">
        <h5><%= f.label :body %></h5>
        <%= f.rich_text_area :body, class: "form-control" %>
    </div>

    <div class="mb-3">
        <h5><%= f.label :image, class: "form-label" %></h5>
        <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png", class: "form-control" %>
    </div>

    <div class="mb-3" data-controller="tom-select">
        <h5><%= f.label :tags, class: "form-label" %></h5>
        <%#= f.select :tag_ids, Tag.where(category: "post").pluck(:name, :id), {}, { multiple: true, id: "select-tags" } %>
        <%= f.select :tag_ids, Tag.all.pluck(:name, :id), {}, { multiple: true, id: "select-tags" } %>
    </div>

    <div class="mb-3">
        <%= f.submit "Submit post", class: "btn btn-dark rounded-pill" %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<% if controller_name == 'profiles' %>
    <li><h5 class="single-post"><%= link_to post.title, post, class: "text-dark" %></h5></li>

<% else controller_name == 'profiles' %>
    <div class="d-flex justify-content-between">
        <h5 class="single-post"><%= link_to post.title, post, class: "text-dark" %></h5>
        <p class="single-post"><%= time_ago_in_words(post.created_at) %> ago</p>
    </div>
    <hr>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title,  "Edit #{@post.title}") %>

<div class="container py-5" style="max-width: 540px">
    <div>
        <%= link_to @post, class: "text-dark" do %>
            <span><i class="bi bi-arrow-left fs-1"></i></span>
            <%# <span class="back">back</span> %>
        <% end %>
    </div>
    <div class="post-copy">
        <h1 class="mb-3">Edit Post</h1>

        <%= render 'form' %>
    </div>
</div>

app/views/posts/index.html.erb
<% provide(:title, "Blog") %>

<div class="container" style="max-width: 750px;">
    <section class="blog py-3 main-profile-section">
        <h1 class="text-center">Software development tutorials</h1>
        <div class="row main-articles-col mt-5">
            <%= render @posts %>
        </div>
    </section>
</div>

app/views/posts/new.html.erb
<% provide(:title, 'New post') %>

<div class="container py-5" style="max-width: 540px">
    <%= link_to :back, class: "text-dark" do %>
        <span><i class="bi bi-arrow-left fs-1"></i></span>
        <%# <span class="back">back</span> %>
    <% end %>
    
    <div class="project-copy">
        <h1 class="mb-3">New Post</h1>

        <%= render 'form' %>
    </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>

<div class="container py-3" style="max-width: 800px">
    <div class="d-flex justify-content-between">
        <%= link_to posts_path, class: "text-dark" do %>
            <span><i class="bi bi-arrow-left fs-1"></i></span>
            <%# <span class="back">back</span> %>
        <% end %>

        <span class="dropdown">
            <% if user_signed_in? && @post.user == current_user %>
                <div style="cursor:pointer;" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-three-dots-vertical fs-3"></i>
                </div>
                <ul class="dropdown-menu">
                    <%= link_to new_post_path, class: "dropdown-item" do %>
                        <i class="bi bi-plus-circle"></i>
                        New post
                    <% end %>
                    <%= link_to edit_post_path(@post), class: "dropdown-item" do %>
                        <i class="bi bi-pen"></i>
                        Edit
                    <% end %>
                    <%= link_to @post, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this post" }, class: "dropdown-item" do %>
                        <i class="bi bi-trash"></i>
                        Delete
                    <% end %>
                </ul>
            <% end %>
        </span>
    </div>
    <div class="post">
        <div class="text-center">
            <h5 class="text-sm text-secondary mb-2"><small><%= time_ago_in_words(@post.created_at) %> ago</small></h5>
            <h1><%= @post.title %></h1>
            
        <div class="py-2 text-center">
            <h5 class="mt-4">Published by:</h5>
            <%= link_to profile_path(@post.user.username), class:"text-dark text-decoration-none" do %>
                <%= gravatar_for @post.user %>
            <% end %>
        </div>
            
            <div class="post-tags mt-3">
                <% @post.tags.each do |tag| %>
                    <%= link_to tag.name, tag, class: "btn btn-light btn-sm border text-sm text-decoration-none" %>
                <% end %>
            </div>
            <div class="post-img my-5 img-fluid">
                <% if @post.image.attached? %>
                    <%= image_tag @post.image, class: "img-fluid" %>
                <% else %>
                    <%= image_tag 'default-webpage.jpg', class: "img-fluid" %>
                <% end %>
            </div>
        </div>
        <p class="trix-content"><%= @post.body %></p>
        <div class="text-center">
            <%= render partial: "likes/button", locals: { likeable: @post } %>
        </div>
    </div>

    <section class="comments mt-4 pb-3 border p-3" style="font-size: 15px;">
        <h3 class="text-center">Comments (<%= @post.comments_count %>)</h3>
        <%= turbo_frame_tag "comments" do %>
            <%= render @post.comments.where(parent_id: nil).includes(:user).order(id: :desc) %>
        <% end %>
        <h6 class="pt-3">New comment:</h6>
        <div id="comment-form" class="comment-form mt-2">
            <%= render 'comments/form', commentable: @commentable, parent: nil %>
        </div>
    </section>
</div>